### ISSUE TITLE
new tool: DuBinary_scan_script

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF#8]
Create a new tool following the examples already available which:

- [x] Scan an existing script for any string containing a path to a file 
on win, a string beggining with: 
`"E:\"` or `"E:/"` or `"/E/"` or `"~/"` or `"~\"`or the same in lower case
on mac, a string beginning with:
`"/something"` or `"~/something"`

- [x] List all those in a table, where the user can select some of them, or all of them, and validates the selection. take care of duplicates, list only once

- [x] Use `DuAEF.DuBinary.convertToIncludeFile()` to convert all files to jsxinc

- [x] move all those jsxinc to a folder (ask the user with `Folder.selectDialog()` )

- [x] Include all those new jsxinc at the very beginning of a new copy of the original script

- [ ] Replace all strings corresponding to converted files with:
if name ends with `'.png'` (case insensitive): `convertedName.binAsString`
else: `DuAEF.DuBinary.toFile(convertedName)`

**Comment by oktomus** [comment]
Comment appelé tr(..) depuis une lib ? Ou je ne dois pas mettre ma fonction finale dans la lib ?

**Comment by oktomus** [comment]
Ce serait cool d'ajouter des fonctions pour afficher de simple fenetre warning

**Comment by Nico-Duduf** [comment]
A priori tu n'as pas besoin d'appeler tr() depuis une lib, puisque dans la lib il n'y  a pas d'UI (enfin, pas tout a fait vrai concernant after et les effets, mais pour l'instant les effets restent en anglais, na!)

Pour ce qui est du tool, qui utilise la lib, mais n'en fait pas "partie", faut juste #include dutranslator dans la fonction principale pour avoir tr() de dispo (d'ailleurs en vrai, si un jour on veut aussi traduire des trucs dans la lib, suffira d'inclure dutranslator dedans, ce qui le rendra aussi dispo à tous les scripts qui incluent la lib, pas plus mal... donc ajouter Dutranslator à DuAEF, je ferai ça au moment de release duik ;) )

**Comment by Nico-Duduf** [comment]
pour les fenetres de warning yen a qqs unes en extendscript
au moins alert("bidule", "titre") mais je crois qu'il y en a d'autres

**Comment by Nico-Duduf** [comment]
au passage si tu ne connais pas, deux adresses vraiment top : 
La doc de extendscript: 
http://estk.aenhancers.com/
La doc spécifique à After: 
http://docs.aenhancers.com/

pour les fenetres alert, c'est dans la classe window de estk: 
http://estk.aenhancers.com/4%20-%20User-Interface%20Tools/window-class.html
ya donc alert() confirm() et prompt()

**Comment by oktomus** [comment]
Sympa merci ! :)

**Comment by oktomus** [comment]
Pour le include dut, vu qu'il nest pas dans DuAEF je le copie temporairement pour dev mais au release tu le mettra c'est ca ?

**Comment by Nico-Duduf** [comment]
ouaip on fait comme ça !

**Comment by Nico-Duduf** [comment]
ou alors en local tu te fais un symlink si tu veux pas ramener le fichier d'un dépot à l'autre

**Comment by Nico-Duduf** [comment]
en plus ya un type qui a fait ça pour faire des liens symboliques super vite sous win : http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html

**Comment by oktomus** [comment]
Oh sympa le tool ! Meme si je suis habitué à ln -s dans git bash, je vais le prendre pour eviter de faire face aux caprices de windows x)

**Comment by oktomus** [comment]
Est-ce que je passe un panel/groupe en parametre dans lequel afficher un tableau ? Ou je créer une nouvelle ui ?

**Comment by Nico-Duduf** [comment]
ouaip et on a pas toujours un bash sous la main ;)
d'ailleurs astuce : je remplace le dossier des scripts de mes différentes versions d'after par un symlink vers un dossier synchro sur tous mes ordis :)
idem pour un sous dossier contenant les plugins tiers

Le seul truc.... c'est que les grosses màj de windows pètent les symlinks et faut les refaire. Con d'OS.

**Comment by Nico-Duduf** [comment]
bah crée une UI, c'est un tool stand alone, ca ira plus vite et c'est aussi simple ;)

**Comment by oktomus** [comment]
Oui je fais pareil xD

**Comment by Nico-Duduf** [comment]
juste une Window avec le tableau et deux boutons quoi

**Comment by oktomus** [comment]
Ok ça marche, je vais essayer de piocher dans Duik pour le tableau, j'ai pas l'habitude avec js

**Comment by Nico-Duduf** [comment]
là : listbox
http://estk.aenhancers.com/4%20-%20User-Interface%20Tools/control-objects.html#control-types-and-creation-parameters

et les méthodes utiles : 
http://estk.aenhancers.com/4%20-%20User-Interface%20Tools/control-objects.html#list-control-object-functions 

;)

**Comment by oktomus** [comment]
je suis sûr que j'étais pas loin de les trouver :3 Merci !

**Comment by oktomus** [comment]
J'ai tout implémenté sauf le dernier point car il nécessite beaucoup de modifs. 
Il faut que je stock les quotes utilisé pour chaque path ainsi que le path d'origine si jamais c'était un chemin relatif qui a été transformé en relatif. 
Ou alors je pourrais faire tous les types de replace ("" absolu, "" relatif, '' absolu, '' relatif) mais je sais pas si ca nécessite beaucoup de ressources. A tester.

**Comment by oktomus** [comment]
@Nico-Duduf, c'est normal d'obtenir ce genre de variable en faisant includeToBinary File?
**var /d/code/open/DuAEF/README = {"binA...**

`DuAEF.DuBinary.convertToIncludeFile(new File("/d/code/open/DuAEF/README"), "", "desktop/something");`

**Comment by oktomus** [comment]
Mise a part le soucis sur les noms de variables, le replace fonctionne.
